hotel/admin_app/urls.py
from django.urls import path
from admin_app.views import *

app_name = 'admin_app'

urlpatterns = [
    path('', StartPageView.as_view(), name='start_page'),
    path('add-room/', AddRoomPageView.as_view(), name='add_room'),
    path('rooms/', RoomsPageView.as_view(), name='rooms'),
    path('rooms/<slug_room>/true', is_hidden_true, name='true'),
    path('rooms/<slug_room>/false', is_hidden_false, name='false'),
    path('book-applications/', BookApplicationsPageView.as_view(), name='book_applications'),
    path('book-applications/<slug_book_application>/', approve_application, name='application_detail'),
    path('application/<slug_book_application>/change_status/', change_status, name='change_status'),
]

hotel/hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client_app.urls', namespace='client_app')),
    path('hotel-admin/', include('admin_app.urls', namespace='admin_app'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/admin_app/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.urls import reverse


class Client(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"


class Comment(models.Model):
    author = models.ForeignKey(Client, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} - {self.date}"


class Room(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(max_length=255, upload_to='images/')

    CHOICE_TYPE = [
        ('Cheap', 'Cheap'),
        ('Comfortable', 'Comfortable'),
        ('V.I.P.', 'V.I.P.')
    ]

    type = models.CharField(max_length=255, choices=CHOICE_TYPE)
    reserved = models.BooleanField(default=False)
    is_hidden = models.BooleanField(default=False)
    comment = models.ForeignKey(Comment,
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.title} - {self.type}"

    def save(self, *args, **kwargs):
        if self.title:
            self.slug = slugify(self.title)
        super(Room, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('slug_room', args=[self.slug])


class Service(models.Model):
    title = models.CharField(max_length=255)
    price = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.title} - {self.price}"


class BookApplication(models.Model):
    client_id = models.ForeignKey(Client, on_delete=models.CASCADE)
    room_id = models.OneToOneField(Room, on_delete=models.CASCADE)
    number_persons = models.IntegerField()
    services = models.ManyToManyField(Service, blank=True)
    start_book = models.DateField()
    end_book = models.DateField()
    total_price = models.PositiveIntegerField(default=0)
    approve_status = models.BooleanField(null=True)

    def __str__(self):
        return f"{self.end_book} {self.total_price} - {self.approve_status}"

    def calculate_total_price(self):
        total = 0
        for service in self.services.all():
            total += service.price
        self.total_price = total
        self.save()

    def get_absolute_url(self):
        return reverse('slug_book_application', args=[self.pk])

hotel/admin_app/forms.py
from django import forms
from admin_app.models import *


class RoomModelForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['title', 'image', 'type']


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'


class BookApplicationForm(forms.ModelForm):
    class Meta:
        model = BookApplication
        fields = ['number_persons', 'services', 'start_book', 'end_book']
        widgets = {
            'start_book': forms.DateInput(attrs={'type': 'date'}),
            'end_book': forms.DateInput(attrs={'type': 'date'})
        }

hotel/admin_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView
from admin_app.forms import *
from admin_app.models import *


class StartPageView(TemplateView):
    template_name = 'admin_app/start_page.html'


class AddRoomPageView(CreateView):
    model = Room
    template_name = 'admin_app/add_room_page.html'
    form_class = RoomModelForm
    success_url = reverse_lazy('admin_app:rooms')


class RoomsPageView(ListView):
    model = Room
    template_name = 'admin_app/rooms_page.html'
    context_object_name = 'rooms'


class BookApplicationsPageView(ListView):
    model = BookApplication
    template_name = 'admin_app/book_application_page.html'
    context_object_name = 'applications'


def is_hidden_true(request, slug_room):
    room = Room.objects.get(slug=slug_room)
    room.is_hidden = True
    room.save()
    return redirect('admin_app:rooms')


def is_hidden_false(request, slug_room):
    room = Room.objects.get(slug=slug_room)
    room.is_hidden = False
    room.save()
    return redirect('admin_app:rooms')


def approve_application(request, slug_book_application):
    application = BookApplication.objects.get(pk=slug_book_application)
    context = {'application': application}
    return render(request, 'admin_app/application_details_page.html', context)


def change_status(request, slug_book_application):
    application = get_object_or_404(BookApplication, pk=slug_book_application)
    room = Room.objects.get(pk=application.room_id.id)

    if request.method == 'POST':
        status = request.POST.get('status')
        if status == 'approve':
            application.approve_status = True
            room.reserved = True
            room.save()
        elif status == 'reject':
            application.approve_status = False
        application.save()

    return redirect('admin_app:book_applications')

hotel/admin_app/templates/admin_app/add_room_page.html
{% extends 'admin_app/base.html' %}

{% block content %}
    <h1>Add Room Page</h1>
    <div class="block_form">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for value in form %}
                <p>{{ value.label }}</p>
                <p>{{ value }}</p>
            {% endfor %}
            <input type="submit" value="Save" class="btn">
            <a href="{% url 'admin_app:rooms' %}"><button class="btn" type="button">Cancel</button></a>
        </form>
    </div>
{% endblock %}

hotel/admin_app/templates/admin_app/application_details_page.html
{% extends 'admin_app/base.html' %}

{% block content %}
    <h1>Book Applications Page</h1>
    <div class="block_detail">
        <div class="element_detail">
            <p><b>Client:</b><br>{{ application.client_id }}</p>
            <p><b>Room numbers::</b><br>{{ application.room_id }}</p>
            <p><b>Number of persons:</b><br>{{ application.number_persons }}</p>
            <p><b>Services:</b><br>
                {% for service in application.services.all %}
                    {{ service.title }},<br>
                {% endfor %}
            </p>

            <p><b>Arrival date:</b><br>{{ application.start_book }}</p>
            <p><b>Date of departure:</b><br>{{ application.end_book }}</p>
            <p><b>Total price:</b><br>{{ application.total_price }}</p>
            <p><b>Approve_status:</b><br>{{ application.approve_status }}</p>
            <form action="{% url 'admin_app:change_status' application.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" name="status" value="approve" class="btn">Approve</button>
                <button type="submit" name="status" value="reject" class="btn">Reject</button>
            </form>
        </div>
    </div>
{% endblock %}

hotel/admin_app/templates/admin_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'admin_app/css/style.css' %}">
</head>
<body>

    <div class="navbar">
        <a href="{% url 'admin_app:start_page' %}"><button class="nav_btn">Home page</button></a>
        <a href="{% url 'admin_app:add_room' %}"><button class="nav_btn">Add a room</button></a>
        <a href="{% url 'admin_app:rooms' %}"><button class="nav_btn">Hotel rooms</button></a>
        <a href="{% url 'admin_app:book_applications' %}"><button class="nav_btn">Reservation requests</button></a>
    </div>

    {% block content %}
    {% endblock %}

</body>
</html>

hotel/admin_app/templates/admin_app/book_application_page.html
{% extends 'admin_app/base.html' %}

{% block content %}
    <h1>Book Applications Page</h1>
    <div class="block">
        {% for application in applications %}
            {% if not application.approve_status == True %}
                <div class="element">
                    <p><b>Client:</b><br>{{ application.client_id }}</p>
                    <p><b>Room numbers::</b><br>{{ application.room_id }}</p>
                    <p><b>Number of persons:</b><br>{{ application.number_persons }}</p>
                    <p><b>Date of departure:</b><br>{{ application.end_book }}</p>
                    <p><b>Total price:</b><br>{{ application.total_price }}</p>
                    <a href="{% url 'admin_app:application_detail' application.pk %}">
                        <button class="btn">Detail</button>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

hotel/admin_app/templates/admin_app/rooms_page.html
{% extends 'admin_app/base.html' %}

{% block content %}
    <h1>Rooms Page</h1>
    <div class="block">
        {% for room in rooms %}
            <div class="element">
                <img src="{{ room.image.url }}" alt="{{ room.title }}" class="img">
                <p><b>Room numbers:</b><br>{{ room.title }}</p>
                <p><b>Category:</b><br>{{ room.type }}</p>
                {% if room.is_hidden == False %}
                    <a href="{% url 'admin_app:true' room.slug %}">
                        <button type="button" class="btn">Hide</button>
                    </a>
                {% else %}
                    <a href="{% url 'admin_app:false' room.slug %}">
                        <button type="button" class="btn">Open</button>
                    </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

hotel/admin_app/templates/admin_app/start_page.html
{% extends 'admin_app/base.html' %}

{% block content %}
    <h1>Start Page</h1>
{% endblock %}