hotel/client_app/urls.py
from django.urls import path
from client_app.views import *

app_name = 'client_app'

urlpatterns = [
    path('', StartPageView.as_view(), name='start_page'),
    path('rooms/', RoomsPageView.as_view(), name='rooms'),
    path('rooms/<slug_room>/', room_detail_page, name='room_detail'),
    path('rooms/<slug_room>/likes/', likes_room, name='likes_room'),
    path('rooms/<slug_room>/book-application/', booking_request_page, name='booking_request'),
    path('books/', application_list, name='application_page'),
    path('books/<slug_book_application>', cancel_request, name='cancel_request'),
]

hotel/hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client_app.urls', namespace='client_app')),
    path('hotel-admin/', include('admin_app.urls', namespace='admin_app'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/client_app/models.py
from django.db import models

# Create your models here.

hotel/client_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from admin_app.forms import *
from admin_app.models import *


class StartPageView(TemplateView):
    template_name = 'client_app/start_page.html'


class RoomsPageView(ListView):
    model = Room
    template_name = 'client_app/rooms_page.html'
    context_object_name = 'rooms'


class RoomDetailPageView(DetailView):
    model = Room
    template_name = 'client_app/room_detail_page.html'
    slug_url_kwarg = 'slug_room'
    context_object_name = 'room'


def room_detail_page(request, slug_room):
    room = Room.objects.get(slug=slug_room)
    if request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            content = form.cleaned_data['content']
            comment = Comment.objects.create(author=author,
                                             content=content)
            room.comment = comment
            room.save()

        return redirect('client_app:rooms')
    else:
        form = CommentModelForm()
    context = {'room': room,
               'comments': Comment.objects.all(),
               'form': form}

    return render(request, 'client_app/room_detail_page.html', context)


# def comment_fun(request, slug_room):
#     room = Room.objects.get(slug=slug_room)
#     if request.method == "POST":
#         form = CommentModelForm(request.POST)
#         if form.is_valid():
#             author = form.cleaned_data['author']
#             content = form.cleaned_data['content']
#             comment = Comment.objects.create(author=author,
#                                              content=content)
#             room.comment = comment
#             room.save()
#
#     return redirect('admin_app:rooms.html')


def booking_request_page(request, slug_room):
    room = Room.objects.get(slug=slug_room)
    if request.method == 'POST':
        form = BookApplicationForm(request.POST)
        if form.is_valid():
            client = Client(first_name=request.POST.get('first_name'),
                            last_name=request.POST.get('last_name'),
                            middle_name=request.POST.get('middle_name'),
                            email=request.POST.get('email'))
            client.save()

            book_application = BookApplication(client_id=client,
                                               room_id=room,
                                               number_persons=form.cleaned_data['number_persons'],
                                               start_book=form.cleaned_data['start_book'],
                                               end_book=form.cleaned_data['end_book'])
            book_application.save()

            services = form.cleaned_data['services']
            for service_id in services:
                book_application.services.add(service_id)
            book_application.calculate_total_price()
            book_application.save()

            return redirect('client_app:start_page')
    else:
        form = BookApplicationForm()

    return render(request, 'client_app/booking_request_page.html', {'form': form})


def likes_room(request, slug_room):
    room = Room.objects.get(slug=slug_room)
    room.likes += 1
    room.save()
    return redirect('client_app:rooms')


def application_list(request):
    application = BookApplication.objects.all()
    if application.exists():
        return render(request, 'client_app/application_page.html', {'applications': application})
    else:
        return redirect('client_app:rooms')


def cancel_request(request, slug_book_application):
    request = BookApplication.objects.get(pk=slug_book_application)
    request.delete()
    return redirect('client_app:rooms')

hotel/client_app/templates/client_app/application_page.html
{% extends 'client_app/base.html' %}

{% block content %}
    <h1>Applications Page</h1>
    <div class="block">
        {% for application in applications %}
            {% if application.approve_status == True %}
                <div class="element status_true">
                    <p><b>Client:</b><br>{{ application.client_id }}</p>
                    <p><b>Room numbers::</b><br>{{ application.room_id }}</p>
                    <p><b>Number of persons:</b><br>{{ application.number_persons }}</p>
                    <p><b>Services:</b><br>{{ application.services }}</p>
                    <p><b>Arrival date:</b><br>{{ application.start_book }}</p>
                    <p><b>Date of departure:</b><br>{{ application.end_book }}</p>
                    <p><b>Total price:</b><br>{{ application.total_price }}</p>
                    <a href="{% url 'client_app:cancel_request' application.pk %}">
                        <button class="btn">Cancel request</button>
                    </a>
                </div>
            {% elif application.approve_status == False %}
                <div class="element status_false">
                    <p><b>Client:</b><br>{{ application.client_id }}</p>
                    <p><b>Room numbers::</b><br>{{ application.room_id }}</p>
                    <p><b>Number of persons:</b><br>{{ application.number_persons }}</p>
                    <p><b>Services:</b><br>{{ application.services }}</p>
                    <p><b>Arrival date:</b><br>{{ application.start_book }}</p>
                    <p><b>Date of departure:</b><br>{{ application.end_book }}</p>
                    <p><b>Total price:</b><br>{{ application.total_price }}</p>
                    <a href="{% url 'client_app:cancel_request' application.pk %}">
                        <button class="btn">Cancel request</button>
                    </a>
                </div>
            {% elif application.approve_status == None %}
                <div class="element">
                    <p><b>Client:</b><br>{{ application.client_id }}</p>
                    <p><b>Room numbers::</b><br>{{ application.room_id }}</p>
                    <p><b>Number of persons:</b><br>{{ application.number_persons }}</p>
                    <p><b>Services:</b><br>{{ application.services }}</p>
                    <p><b>Arrival date:</b><br>{{ application.start_book }}</p>
                    <p><b>Date of departure:</b><br>{{ application.end_book }}</p>
                    <p><b>Total price:</b><br>{{ application.total_price }}</p>
                    <a href="{% url 'client_app:cancel_request' application.pk %}">
                        <button class="btn">Cancel request</button>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

hotel/client_app/templates/client_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'client_app/css/style.css' %}">
</head>
<body>

    <div class="navbar">
        <a href="{% url 'client_app:start_page' %}"><button class="nav_btn">Home page</button></a>
        <a href="{% url 'client_app:rooms' %}"><button class="nav_btn">Hotel rooms</button></a>
        <a href="{% url 'client_app:application_page' %}"><button class="nav_btn">Application</button></a>
    </div>

    {% block content %}
    {% endblock %}

</body>
</html>

hotel/client_app/templates/client_app/booking_request_page.html
{% extends 'client_app/base.html' %}

{% block content %}
    <h1>Booking page</h1>
    <div class="block_form">
        <form action="" method="post">
            {% csrf_token %}
            <label>First name</label><br>
            <input type="text" name="first_name"><br>
            <label>Last name</label><br>
            <input type="text" name="last_name"><br>
            <label>Middle name</label><br>
            <input type="text" name="middle_name"><br>
            <label>Email</label><br>
            <input type="text" name="email"><br>
            {% for value in form %}
                <p>{{ value.label }}</p>
                <p>{{ value }}</p>
            {% endfor %}
            <input type="submit" value="Save" class="btn">
            <a href="{% url 'client_app:rooms' %}"><button class="btn" type="button">Cancel</button></a>
        </form>
    </div>
{% endblock %}

hotel/client_app/templates/client_app/room_detail_page.html
{% extends 'client_app/base.html' %}

{% block content %}
    <h1>Room Detail Page</h1>
    <div class="block_detail">
        <img src="{{ room.image.url }}" alt="{{ room.title }}" class="img_detail">
        <p><b>Room numbers:</b><br>{{ room.title }}</p>
        <p><b>Category:</b><br>{{ room.type }}</p>
        <p><b>Likes:</b><br>{{ room.likes }}</p>
        <a href="{% url 'client_app:booking_request' room.slug %}"><button class="btn">Book a room</button></a>
    </div>
    <div class="block_form">
        <h3>Add comment</h3>
            <form action="" method="post">
                {% csrf_token %}
                <p>{{ form.as_p }}</p>
                <input type="submit" value="Save" class="btn">
            </form>
        </div>
    <h1>Comments</h1>
    {% for comment in comments %}
        {% if room.comment == comment %}
            <div class="element_comment">
                <p><b>Author: </b>{{ comment.author }}</p>
                <p>{{ comment.content }}</p>
                <p><b>Date: </b>{{ comment.date }}</p>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

hotel/client_app/templates/client_app/rooms_page.html
{% extends 'client_app/base.html' %}

{% block content %}
    <h1>Rooms Page</h1>
    <div class="block">
        {% for room in rooms %}
            {% if room.reserved == False and room.is_hidden == False %}
            <div class="element">
                <img src="{{ room.image.url }}" alt="{{ room.title }}" class="img">
                <p><b>Room numbers:</b><br>{{ room.title }}</p>
                <p><b>Category:</b><br>{{ room.type }}</p>
                <a href="{% url 'client_app:room_detail' room.slug %}"><button class="btn">Detail</button></a>
                <a href="{% url 'client_app:likes_room' room.slug %}">
                    <button class="btn">Likes {{ room.likes }}</button>
                </a>
            </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

hotel/client_app/templates/client_app/start_page.html
{% extends 'client_app/base.html' %}

{% block content %}
    <h1>Start Page</h1>
{% endblock %}